FROM node:24-alpine
WORKDIR /usr/app

COPY package.json ./
RUN npm install

COPY src src
COPY testserver testserver
COPY testserver/tsconfig.json ./

CMD [ "node", "-r", "ts-node/register", "--no-warnings", "--inspect=0.0.0.0", "testserver/index.ts" ]
