version: '3'
services:
  fastify-test:
    build:
      context: .
    depends_on:
      - fastify-http
      - fastify-https
  fastify-http:
    build:
      context: .
      dockerfile: Dockerfile.http
    environment:
      NODE_ENV: development
  fastify-https:
    build:
      context: .
      dockerfile: Dockerfile.https
