FROM txstatemws/keygenerator as keygen

FROM node:20-alpine
WORKDIR /usr/app

COPY package.json ./
RUN npm install

COPY --from=keygen /securekeys /securekeys
COPY src src
COPY testserver testserver
COPY testserver/tsconfig.json ./

CMD [ "node", "-r", "ts-node/register", "--no-warnings", "testserver/index.ts" ]
