FROM txstatemws/keygenerator AS keygen

FROM node:24-alpine
WORKDIR /usr/app

COPY package.json ./
RUN npm install

COPY --from=keygen /securekeys /securekeys
COPY src src
COPY testserver testserver

CMD [ "node", "--experimental-transform-types", "--no-warnings", "testserver/index.ts" ]
